module.exports = {
  lng: 'en',
  resources: {
    en: {
      translation: {
        "en": "en",
        "Update Agent": "Update Agent",
        "Language translation initialized": "Language translation initialized: en",
        "Website": "Website",
        "View": "View",
        "Reload": "Reload",
        "Toggle Developer Tools": "Toggle Developer Tools",
        "Edit": "Edit",
        "Undo": "Undo",
        "Redo": "Redo",
        "Cut": "Cut",
        "Copy": "Copy",
        "Paste": "Paste",
        "Quit": "Quit",
        "Select All": "Select All",
        "TRIGGERcmd Agent Sign In": "TRIGGERcmd Agent Sign In",
        "Background Service": "Background Service",
        "Install Background Service": "Install Background Service",
        "Remove Background Service": "Remove Background Service",
        "Text Command Editor": "Text Command Editor",
        "GUI Command Editor": "GUI Command Editor",
        "Version": "Version",
        "Language": "Language"
      }
    },
    pt: {
      translation: {
        "en": "pt",
        "Update Agent": "Agente de atualização",
        "Language translation initialized": "Tradução de idioma inicializada: pt",
        "Website": "Local na rede Internet",
        "View": "Visão",
        "Reload": "Recarregar",
        "Toggle Developer Tools": "Ferramentas do Desenvolvedor",
        "Edit": "Editar",
        "Undo": "Desfazer",
        "Redo": "Refazer",
        "Cut": "Corte",
        "Copy": "Cópia de",
        "Paste": "Colar",
        "Quit": "Desistir",
        "Select All": "Selecionar Tudo",
        "TRIGGERcmd Agent Sign In": "Login do agente TRIGGERcmd",
        "Background Service": "Background Serviço",
        "Install Background Service": "Instalar Serviço Background",
        "Remove Background Service": "Remover Serviço Background",
        "Text Command Editor": "Editor de comandos de texto",
        "GUI Command Editor": "Editor de Comandos GUI",
        "Version": "Versão",
        "Language": "Língua"
      }
    },
    es: {
      translation: {
        "en": "es",
        "Update Agent": "Agente de actualización",
        "Language translation initialized": "Traducción de idioma inicializada: es",
        "Website": "Sitio web",
        "View": "Vista",
        "Reload": "Recargar",
        "Toggle Developer Tools": "Toggle Herramientas para desarrolladores",
        "Edit": "Editar",
        "Undo": "Deshacer",
        "Redo": "Rehacer",
        "Cut": "Cortar",
        "Copy": "Copiar",
        "Paste": "Pegar",
        "Quit": "Abandonar",
        "Select All": "Seleccionar todo",
        "TRIGGERcmd Agent Sign In": "Inicio de sesión del agente TRIGGERcmd",
        "Background Service": "Servicio de fondo",
        "Install Background Service": "Instalar servicio en segundo plano",
        "Remove Background Service": "Eliminar servicio en segundo plano",
        "Text Command Editor": "Editor de comandos de texto",
        "GUI Command Editor": "Editor de comandos GUI",
        "Version": "Versión",
        "Language": "Idioma"
      }
    },
    de: {
      translation: {
        "en": "de",
        "Update Agent": "Update-Agent", // tl note: it seems english is used in this context
        "Language translation initialized": "Sprachübersetzung initialisiert: de",
        "Website": "Webseite",
        "View": "Anzeige",
        "Reload": "Neu laden",
        "Toggle Developer Tools": "Entwicklertools umschalten",
        "Edit": "Bearbeiten",
        "Undo": "Rückgängig machen",
        "Redo": "Wiederholen",
        "Cut": "Ausschneiden",
        "Copy": "Kopieren",
        "Paste": "Einfügen",
        "Quit": "Aufhören",
        "Select All": "Wählen Sie Alle",
        "TRIGGERcmd Agent Sign In": "TRIGGERcmd Agent Einloggen",
        "Background Service": "Hintergrunddienst",
        "Install Background Service": "Installieren Sie den Hintergrunddienst",
        "Remove Background Service": "Entfernen Sie den Hintergrunddienst",
        "Text Command Editor": "Textbefehls-Editor",
        "GUI Command Editor": "GUI-Befehls-Editor",
        "Version": "Ausführung",
        "Language": "Sprache"
      }
    },
    fr: {
      translation: {
        "en": "fr",
        "Update Agent": "Agent de mise à jour",
        "Language translation initialized": "Traduction de langue initialisée: fr",
        "Website": "Site Internet",
        "View": "Voir",
        "Reload": "Recharger",
        "Toggle Developer Tools": "Basculer les outils de développement",
        "Edit": "Éditer",
        "Undo": "Annuler",
        "Redo": "Refaire",
        "Cut": "Couper",
        "Copy": "Copier",
        "Paste": "Coller",
        "Quit": "Quitter",
        "Select All": "Tout sélectionner",
        "TRIGGERcmd Agent Sign In": "Connexion de l'agent TRIGGERcmd",
        "Background Service": "Service d'arrière-plan",
        "Install Background Service": "Installer le service d'arrière-plan",
        "Remove Background Service": "Supprimer le service d'arrière-plan",
        "Text Command Editor": "Éditeur de commandes de texte",
        "GUI Command Editor": "Éditeur de commandes GUI",
        "Version": "Version",
        "Language": "Langue"
      }
    },
    it: {
      translation: {
        "en": "it",
        "Update Agent": "Agente di aggiornamento",
        "Language translation initialized": "Traduzione linguistica inizializzata: it",
        "Website": "Sito web",
        "View": "Vedere",
        "Reload": "Ricaricare",
        "Toggle Developer Tools": "Attiva/disattiva Strumenti per sviluppatori",
        "Edit": "Modificare",
        "Undo": "Annullare",
        "Redo": "Rifare",
        "Cut": "Taglia",
        "Copy": "Copia",
        "Paste": "Incolla",
        "Quit": "Uscire",
        "Select All": "Seleziona tutto",
        "TRIGGERcmd Agent Sign In": "Accesso agente TRIGGERcmd",
        "Background Service": "Servizio in background",
        "Install Background Service": "Installa il servizio in background",
        "Remove Background Service": "Rimuovi servizio in background",
        "Text Command Editor": "Editor di comandi di testo",
        "GUI Command Editor": "Editor dei comandi della GUI",
        "Version": "Versione",
        "Language": "Linguaggio"
      }
    },
    jp: {
      translation: {
        "en": "jp",
        "Update Agent": "更新エージェント",
        "Language translation initialized": "初期化された言語翻訳: jp",
        "Website": "ウェブサイト",
        "View": "眺める",
        "Reload": "リロード",
        "Toggle Developer Tools": "開発者ツールの切り替え",
        "Edit": "編集",
        "Undo": "アンドゥ",
        "Redo": "やり直す",
        "Cut": "カット",
        "Copy": "コピー",
        "Paste": "ペースト",
        "Quit": "終了する",
        "Select All": "すべて選択",
        "TRIGGERcmd Agent Sign In": "TRIGGERcmd エージェントのサインイン",
        "Background Service": "バックグラウンド サービス",
        "Install Background Service": "バックグラウンド サービスをインストールする",
        "Remove Background Service": "バックグラウンド サービスを削除する",
        "Text Command Editor": "テキスト コマンド エディタ",
        "GUI Command Editor": "GUI コマンド エディタ",
        "Version": "バージョン",
        "Language": "言語"
      }
    }
  },
  compatibilityJSON: 'v3',
  interpolation: {
    escapeValue: false
  },
  saveMissing: true,
  fallbackLng: 'en',
  whitelist: ['pt', 'en', 'es', 'de', 'fr', 'it', 'jp'],
  react: {
    wait: false
  }
};
