blueprint:
  name: TRIGGERcmd switch on
  description: Trigger command when entity turns on.
  domain: automation
  source_url: https://github.com/rvmey/TRIGGERcmd-Agent/blob/master/ha_blueprints/on_switch.yaml
  author: TRIGGERcmd
  input:
    trigger_entity:
      name: Trigger Entities
      description: Select entities with on/off state.
      selector:
        entity:
          multiple: true
    switch_target:
      name: switch
      description: Select your TRIGGERcmd switch entity.
      selector:
        target:
          entity:
          - domain:
            - switch
mode: restart
max_exceeded: silent
triggers:
  trigger: state
  entity_id: !input trigger_entity
  from: 'off'
  to: 'on'
actions:
- alias: Turn on the switch
  action: switch.turn_on
  target: !input switch_target
